2024-08-20 17:30:17.712530: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /nfs/dust/cms/user/puschman/tf_venv/lib64:/nfs/dust/cms/user/puschman/rivet/lib:/nfs/dust/cms/user/puschman/rivet/lib64:/nfs/dust/cms/user/puschman/rivet/lib64:/nfs/dust/cms/user/puschman/rivet/lib64:/nfs/dust/cms/user/puschman/rivet/lib64:/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.32.02/x86_64-almalinux9.4-gcc114-opt/lib:/cvmfs/sft.cern.ch/lcg/releases/LCG_106_cuda/cuda/12.4/x86_64-el9-gcc11-opt/lib64/cmake:/cvmfs/sft.cern.ch/lcg/releases/LCG_106_cuda/cuda/12.4/x86_64-el9-gcc11-opt/lib64/stubs:/cvmfs/sft.cern.ch/lcg/releases/LCG_106_cuda/cuda/12.4/x86_64-el9-gcc11-opt/lib64:/cvmfs/sft.cern.ch/lcg/releases/LCG_106_cuda/cudnn/9.1.1.17/x86_64-el9-gcc11-opt/lib64:/cvmfs/sft.cern.ch/lcg/releases/LCG_106_cuda/cudnn/9.1.1.17/x86_64-el9-gcc11-opt/lib:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-de683/x86_64-el9/lib:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-de683/x86_64-el9/lib64:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/lib:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-de683/x86_64-el9/lib:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-de683/x86_64-el9/lib64:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/lib
2024-08-20 17:30:17.712880: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "/nfs/dust/cms/user/puschman/DCTR_Paper/DCTR_FP/20240820_MSE_vs_BCE/./submit_DCTR_training_neural_positive_MSE_vs_BCE.py", line 25, in <module>
    process_id = args.p
AttributeError: 'Namespace' object has no attribute 'p'
